### ISSUE TITLE
Publish POST fails in Chrome/Firefox over HTTPS

### ISSUE THREAD

**Issue by nickdunn** [perfectsense/brightspot-cms#210] opened 2015-07-13 15:29 UTC
When running over HTTPS, clicking "Publish" when saving an entry in a modal window (e.g. editing a related entry from its parent) the AJAX POST is made over HTTP. This works in Safari but Chrome and Firefox block the request:

    Blocked loading mixed active content "http://.../cms/content/edit.jsp?action-publish=true&undefined&_frame=true&typeId=...&id=...&published=1436801042709

Is this a bug with the way that the AJAX request's URL is resolved?

**Comment by markpfletcher** [comment] 2015-07-27 17:00
Hi - I just wondered if there was a fix for this issue?

**Comment by catwoods** [comment] 2015-09-03 07:33
Hi, is this resolved yet?

**Comment by nickdunn** [comment] 2015-09-03 15:48
Let me know if I can provide any extra information to help with this. Has anyone else found the same thing when running Brightspot over HTTPS?

**Comment by hyoolim** [comment] 2016-06-24 16:59
This is most likely caused by Tomcat not recognizing that the initial connection was over HTTPS. We use https://github.com/perfectsense/dari/blob/75633c804e5bb294ac122dc19212a26580b54e80/util/src/main/java/com/psddev/dari/util/JspUtils.java#L605 to detect it, and your environment is probably set up in such way that there's nothing that the system can use to recognize HTTPS connection.

I'm closing this issue for now, as there hasn't been any activity in some time, but if you're still having problems, please feel free to reopen.

Going forward, we'll be more closely monitoring the issues here so that the questions don't go unanswered for so long.

**Closed by hyoolim** 2016-06-24 16:59 UTC
